# When...
# - A commit is pushed to main
# - A pull request is opened
# This workflow will...
# - Run tests using node

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install npm dependencies
        run: npm ci --ignore-scripts
      - name: Run validation
        run: npm run validate
